version: "3"
services:
  analytics_pipeline:
    image: edxops/analytics_pipeline:latest
    environment:
      - DEFAULT_USER=hadoop
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
    - /edx/app/hadoop/repo:/edx/app/analytics_pipeline/analytics_pipeline
    command: bash
